<?php

namespace App\Domain\User\VO;

use MyCLabs\Enum\Enum;

/**
 * @method static ISO2Code AF()
 * @method static ISO2Code AX()
 * @method static ISO2Code AL()
 * @method static ISO2Code DZ()
 * @method static ISO2Code AS()
 * @method static ISO2Code AD()
 * @method static ISO2Code AO()
 * @method static ISO2Code AI()
 * @method static ISO2Code AQ()
 * @method static ISO2Code AG()
 * @method static ISO2Code AR()
 * @method static ISO2Code AM()
 * @method static ISO2Code AW()
 * @method static ISO2Code AU()
 * @method static ISO2Code AT()
 * @method static ISO2Code AZ()
 * @method static ISO2Code BH()
 * @method static ISO2Code BS()
 * @method static ISO2Code BD()
 * @method static ISO2Code BB()
 * @method static ISO2Code BY()
 * @method static ISO2Code BE()
 * @method static ISO2Code BZ()
 * @method static ISO2Code BJ()
 * @method static ISO2Code BM()
 * @method static ISO2Code BT()
 * @method static ISO2Code BO()
 * @method static ISO2Code BQ()
 * @method static ISO2Code BA()
 * @method static ISO2Code BW()
 * @method static ISO2Code BV()
 * @method static ISO2Code BR()
 * @method static ISO2Code IO()
 * @method static ISO2Code BN()
 * @method static ISO2Code BG()
 * @method static ISO2Code BF()
 * @method static ISO2Code BI()
 * @method static ISO2Code KH()
 * @method static ISO2Code CM()
 * @method static ISO2Code CA()
 * @method static ISO2Code CV()
 * @method static ISO2Code KY()
 * @method static ISO2Code CF()
 * @method static ISO2Code TD()
 * @method static ISO2Code CL()
 * @method static ISO2Code CN()
 * @method static ISO2Code CX()
 * @method static ISO2Code CC()
 * @method static ISO2Code CO()
 * @method static ISO2Code KM()
 * @method static ISO2Code CG()
 * @method static ISO2Code CD()
 * @method static ISO2Code CK()
 * @method static ISO2Code CR()
 * @method static ISO2Code CI()
 * @method static ISO2Code HR()
 * @method static ISO2Code CU()
 * @method static ISO2Code CW()
 * @method static ISO2Code CY()
 * @method static ISO2Code CZ()
 * @method static ISO2Code DK()
 * @method static ISO2Code DJ()
 * @method static ISO2Code DM()
 * @method static ISO2Code DO()
 * @method static ISO2Code EC()
 * @method static ISO2Code EG()
 * @method static ISO2Code SV()
 * @method static ISO2Code GQ()
 * @method static ISO2Code ER()
 * @method static ISO2Code EE()
 * @method static ISO2Code ET()
 * @method static ISO2Code FK()
 * @method static ISO2Code FO()
 * @method static ISO2Code FJ()
 * @method static ISO2Code FI()
 * @method static ISO2Code FR()
 * @method static ISO2Code GF()
 * @method static ISO2Code PF()
 * @method static ISO2Code TF()
 * @method static ISO2Code GA()
 * @method static ISO2Code GM()
 * @method static ISO2Code GE()
 * @method static ISO2Code DE()
 * @method static ISO2Code GH()
 * @method static ISO2Code GI()
 * @method static ISO2Code GR()
 * @method static ISO2Code GL()
 * @method static ISO2Code GD()
 * @method static ISO2Code GP()
 * @method static ISO2Code GU()
 * @method static ISO2Code GT()
 * @method static ISO2Code GG()
 * @method static ISO2Code GN()
 * @method static ISO2Code GW()
 * @method static ISO2Code GY()
 * @method static ISO2Code HT()
 * @method static ISO2Code HM()
 * @method static ISO2Code VA()
 * @method static ISO2Code HN()
 * @method static ISO2Code HK()
 * @method static ISO2Code HU()
 * @method static ISO2Code IS()
 * @method static ISO2Code IN()
 * @method static ISO2Code ID()
 * @method static ISO2Code IR()
 * @method static ISO2Code IQ()
 * @method static ISO2Code IE()
 * @method static ISO2Code IM()
 * @method static ISO2Code IL()
 * @method static ISO2Code IT()
 * @method static ISO2Code JM()
 * @method static ISO2Code JP()
 * @method static ISO2Code JE()
 * @method static ISO2Code JO()
 * @method static ISO2Code KZ()
 * @method static ISO2Code KE()
 * @method static ISO2Code KI()
 * @method static ISO2Code KP()
 * @method static ISO2Code KR()
 * @method static ISO2Code KW()
 * @method static ISO2Code KG()
 * @method static ISO2Code LA()
 * @method static ISO2Code LV()
 * @method static ISO2Code LB()
 * @method static ISO2Code LS()
 * @method static ISO2Code LR()
 * @method static ISO2Code LY()
 * @method static ISO2Code LI()
 * @method static ISO2Code LT()
 * @method static ISO2Code LU()
 * @method static ISO2Code MO()
 * @method static ISO2Code MK()
 * @method static ISO2Code MG()
 * @method static ISO2Code MW()
 * @method static ISO2Code MY()
 * @method static ISO2Code MV()
 * @method static ISO2Code ML()
 * @method static ISO2Code MT()
 * @method static ISO2Code MH()
 * @method static ISO2Code MQ()
 * @method static ISO2Code MR()
 * @method static ISO2Code MU()
 * @method static ISO2Code YT()
 * @method static ISO2Code MX()
 * @method static ISO2Code FM()
 * @method static ISO2Code MD()
 * @method static ISO2Code MC()
 * @method static ISO2Code MN()
 * @method static ISO2Code ME()
 * @method static ISO2Code MS()
 * @method static ISO2Code MA()
 * @method static ISO2Code MZ()
 * @method static ISO2Code MM()
 * @method static ISO2Code NA()
 * @method static ISO2Code NR()
 * @method static ISO2Code NP()
 * @method static ISO2Code NL()
 * @method static ISO2Code NC()
 * @method static ISO2Code NZ()
 * @method static ISO2Code NI()
 * @method static ISO2Code NE()
 * @method static ISO2Code NG()
 * @method static ISO2Code NU()
 * @method static ISO2Code NF()
 * @method static ISO2Code MP()
 * @method static ISO2Code NO()
 * @method static ISO2Code OM()
 * @method static ISO2Code PK()
 * @method static ISO2Code PW()
 * @method static ISO2Code PS()
 * @method static ISO2Code PA()
 * @method static ISO2Code PG()
 * @method static ISO2Code PY()
 * @method static ISO2Code PE()
 * @method static ISO2Code PH()
 * @method static ISO2Code PN()
 * @method static ISO2Code PL()
 * @method static ISO2Code PT()
 * @method static ISO2Code PR()
 * @method static ISO2Code QA()
 * @method static ISO2Code RE()
 * @method static ISO2Code RO()
 * @method static ISO2Code RU()
 * @method static ISO2Code RW()
 * @method static ISO2Code BL()
 * @method static ISO2Code SH()
 * @method static ISO2Code KN()
 * @method static ISO2Code LC()
 * @method static ISO2Code MF()
 * @method static ISO2Code PM()
 * @method static ISO2Code VC()
 * @method static ISO2Code WS()
 * @method static ISO2Code SM()
 * @method static ISO2Code ST()
 * @method static ISO2Code SA()
 * @method static ISO2Code SN()
 * @method static ISO2Code RS()
 * @method static ISO2Code SC()
 * @method static ISO2Code SL()
 * @method static ISO2Code SG()
 * @method static ISO2Code SX()
 * @method static ISO2Code SK()
 * @method static ISO2Code SI()
 * @method static ISO2Code SB()
 * @method static ISO2Code SO()
 * @method static ISO2Code ZA()
 * @method static ISO2Code GS()
 * @method static ISO2Code SS()
 * @method static ISO2Code ES()
 * @method static ISO2Code LK()
 * @method static ISO2Code SD()
 * @method static ISO2Code SR()
 * @method static ISO2Code SJ()
 * @method static ISO2Code SZ()
 * @method static ISO2Code SE()
 * @method static ISO2Code CH()
 * @method static ISO2Code SY()
 * @method static ISO2Code TW()
 * @method static ISO2Code TJ()
 * @method static ISO2Code TZ()
 * @method static ISO2Code TH()
 * @method static ISO2Code TL()
 * @method static ISO2Code TG()
 * @method static ISO2Code TK()
 * @method static ISO2Code TO()
 * @method static ISO2Code TT()
 * @method static ISO2Code TN()
 * @method static ISO2Code TR()
 * @method static ISO2Code TM()
 * @method static ISO2Code TC()
 * @method static ISO2Code TV()
 * @method static ISO2Code UG()
 * @method static ISO2Code UA()
 * @method static ISO2Code AE()
 * @method static ISO2Code GB()
 * @method static ISO2Code US()
 * @method static ISO2Code UM()
 * @method static ISO2Code UY()
 * @method static ISO2Code UZ()
 * @method static ISO2Code VU()
 * @method static ISO2Code VE()
 * @method static ISO2Code VN()
 * @method static ISO2Code VG()
 * @method static ISO2Code VI()
 * @method static ISO2Code WF()
 * @method static ISO2Code EH()
 * @method static ISO2Code YE()
 * @method static ISO2Code ZM()
 * @method static ISO2Code ZW()
 */
class ISO2Code extends Enum
{
    public const AF = "AF";
    public const AX = "AX";
    public const AL = "AL";
    public const DZ = "DZ";
    public const AS = "AS";
    public const AD = "AD";
    public const AO = "AO";
    public const AI = "AI";
    public const AQ = "AQ";
    public const AG = "AG";
    public const AR = "AR";
    public const AM = "AM";
    public const AW = "AW";
    public const AU = "AU";
    public const AT = "AT";
    public const AZ = "AZ";
    public const BH = "BH";
    public const BS = "BS";
    public const BD = "BD";
    public const BB = "BB";
    public const BY = "BY";
    public const BE = "BE";
    public const BZ = "BZ";
    public const BJ = "BJ";
    public const BM = "BM";
    public const BT = "BT";
    public const BO = "BO";
    public const BQ = "BQ";
    public const BA = "BA";
    public const BW = "BW";
    public const BV = "BV";
    public const BR = "BR";
    public const IO = "IO";
    public const BN = "BN";
    public const BG = "BG";
    public const BF = "BF";
    public const BI = "BI";
    public const KH = "KH";
    public const CM = "CM";
    public const CA = "CA";
    public const CV = "CV";
    public const KY = "KY";
    public const CF = "CF";
    public const TD = "TD";
    public const CL = "CL";
    public const CN = "CN";
    public const CX = "CX";
    public const CC = "CC";
    public const CO = "CO";
    public const KM = "KM";
    public const CG = "CG";
    public const CD = "CD";
    public const CK = "CK";
    public const CR = "CR";
    public const CI = "CI";
    public const HR = "HR";
    public const CU = "CU";
    public const CW = "CW";
    public const CY = "CY";
    public const CZ = "CZ";
    public const DK = "DK";
    public const DJ = "DJ";
    public const DM = "DM";
    public const DO = "DO";
    public const EC = "EC";
    public const EG = "EG";
    public const SV = "SV";
    public const GQ = "GQ";
    public const ER = "ER";
    public const EE = "EE";
    public const ET = "ET";
    public const FK = "FK";
    public const FO = "FO";
    public const FJ = "FJ";
    public const FI = "FI";
    public const FR = "FR";
    public const GF = "GF";
    public const PF = "PF";
    public const TF = "TF";
    public const GA = "GA";
    public const GM = "GM";
    public const GE = "GE";
    public const DE = "DE";
    public const GH = "GH";
    public const GI = "GI";
    public const GR = "GR";
    public const GL = "GL";
    public const GD = "GD";
    public const GP = "GP";
    public const GU = "GU";
    public const GT = "GT";
    public const GG = "GG";
    public const GN = "GN";
    public const GW = "GW";
    public const GY = "GY";
    public const HT = "HT";
    public const HM = "HM";
    public const VA = "VA";
    public const HN = "HN";
    public const HK = "HK";
    public const HU = "HU";
    public const IS = "IS";
    public const IN = "IN";
    public const ID = "ID";
    public const IR = "IR";
    public const IQ = "IQ";
    public const IE = "IE";
    public const IM = "IM";
    public const IL = "IL";
    public const IT = "IT";
    public const JM = "JM";
    public const JP = "JP";
    public const JE = "JE";
    public const JO = "JO";
    public const KZ = "KZ";
    public const KE = "KE";
    public const KI = "KI";
    public const KP = "KP";
    public const KR = "KR";
    public const KW = "KW";
    public const KG = "KG";
    public const LA = "LA";
    public const LV = "LV";
    public const LB = "LB";
    public const LS = "LS";
    public const LR = "LR";
    public const LY = "LY";
    public const LI = "LI";
    public const LT = "LT";
    public const LU = "LU";
    public const MO = "MO";
    public const MK = "MK";
    public const MG = "MG";
    public const MW = "MW";
    public const MY = "MY";
    public const MV = "MV";
    public const ML = "ML";
    public const MT = "MT";
    public const MH = "MH";
    public const MQ = "MQ";
    public const MR = "MR";
    public const MU = "MU";
    public const YT = "YT";
    public const MX = "MX";
    public const FM = "FM";
    public const MD = "MD";
    public const MC = "MC";
    public const MN = "MN";
    public const ME = "ME";
    public const MS = "MS";
    public const MA = "MA";
    public const MZ = "MZ";
    public const MM = "MM";
    public const NA = "NA";
    public const NR = "NR";
    public const NP = "NP";
    public const NL = "NL";
    public const NC = "NC";
    public const NZ = "NZ";
    public const NI = "NI";
    public const NE = "NE";
    public const NG = "NG";
    public const NU = "NU";
    public const NF = "NF";
    public const MP = "MP";
    public const NO = "NO";
    public const OM = "OM";
    public const PK = "PK";
    public const PW = "PW";
    public const PS = "PS";
    public const PA = "PA";
    public const PG = "PG";
    public const PY = "PY";
    public const PE = "PE";
    public const PH = "PH";
    public const PN = "PN";
    public const PL = "PL";
    public const PT = "PT";
    public const PR = "PR";
    public const QA = "QA";
    public const RE = "RE";
    public const RO = "RO";
    public const RU = "RU";
    public const RW = "RW";
    public const BL = "BL";
    public const SH = "SH";
    public const KN = "KN";
    public const LC = "LC";
    public const MF = "MF";
    public const PM = "PM";
    public const VC = "VC";
    public const WS = "WS";
    public const SM = "SM";
    public const ST = "ST";
    public const SA = "SA";
    public const SN = "SN";
    public const RS = "RS";
    public const SC = "SC";
    public const SL = "SL";
    public const SG = "SG";
    public const SX = "SX";
    public const SK = "SK";
    public const SI = "SI";
    public const SB = "SB";
    public const SO = "SO";
    public const ZA = "ZA";
    public const GS = "GS";
    public const SS = "SS";
    public const ES = "ES";
    public const LK = "LK";
    public const SD = "SD";
    public const SR = "SR";
    public const SJ = "SJ";
    public const SZ = "SZ";
    public const SE = "SE";
    public const CH = "CH";
    public const SY = "SY";
    public const TW = "TW";
    public const TJ = "TJ";
    public const TZ = "TZ";
    public const TH = "TH";
    public const TL = "TL";
    public const TG = "TG";
    public const TK = "TK";
    public const TO = "TO";
    public const TT = "TT";
    public const TN = "TN";
    public const TR = "TR";
    public const TM = "TM";
    public const TC = "TC";
    public const TV = "TV";
    public const UG = "UG";
    public const UA = "UA";
    public const AE = "AE";
    public const GB = "GB";
    public const US = "US";
    public const UM = "UM";
    public const UY = "UY";
    public const UZ = "UZ";
    public const VU = "VU";
    public const VE = "VE";
    public const VN = "VN";
    public const VG = "VG";
    public const VI = "VI";
    public const WF = "WF";
    public const EH = "EH";
    public const YE = "YE";
    public const ZM = "ZM";
    public const ZW = "ZW";
}
